### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by xhw205** [bojone/GlobalPointer#1]
请问 大大这是什么错误呀
环境：
python3.8
tensorflow 1.5.1
keras2.3.1
bert4keras-0.10.6

出错过程：
2021-07-21 23:23:30.850241: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-07-21 23:23:30.850272: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-07-21 23:23:30.850304: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2021-07-21 23:23:30.850334: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-07-21 23:23:30.850365: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-07-21 23:23:30.855468: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1794] Adding visible gpu devices: 0
2021-07-21 23:23:30.855547: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-07-21 23:23:31.146373: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-21 23:23:31.146412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212]      0
2021-07-21 23:23:31.146418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 0:   N
2021-07-21 23:23:31.147960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21829 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3090, pci bus id: 0000:d5:00.0, compute capability: 8.6)
WARNING:tensorflow:From /home/xhw205/.environments/venv/lib/python3.8/site-packages/bert4keras/layers.py:1199: The name tf.matrix_band_part is deprecated. Please use tf.linalg.band_part instead.

WARNING:tensorflow:From /home/xhw205/.environments/venv/lib/python3.8/site-packages/bert4keras/layers.py:1199: The name tf.matrix_band_part is deprecated. Please use tf.linalg.band_part instead.

Traceback (most recent call last):
  File "glp.py", line 103, in <module>
    model = Model(model.input, output)
  File "/home/xhw205/.environments/venv/lib/python3.8/site-packages/tensorflow_core/python/keras/engine/training.py", line 147, in __init__
    super(Model, self).__init__(*args, **kwargs)
  File "/home/xhw205/.environments/venv/lib/python3.8/site-packages/tensorflow_core/python/keras/engine/network.py", line 164, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home/xhw205/.environments/venv/lib/python3.8/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/xhw205/.environments/venv/lib/python3.8/site-packages/tensorflow_core/python/keras/engine/network.py", line 270, in _init_graph_network
    self._validate_graph_inputs_and_outputs()
  File "/home/xhw205/.environments/venv/lib/python3.8/site-packages/tensorflow_core/python/keras/engine/network.py", line 1482, in _validate_graph_inputs_and_outputs
    layer = x._keras_history.layer
AttributeError: 'tuple' object has no attribute 'layer'

**Comment by xhw205** [comment]
找到了，是我 tensorflow.keras,和keras混用了
